### ISSUE TITLE
Spider: Allegheny County Airport Authority

### ISSUE THREAD

**Issue by pjsier** [bonfirefan/city-scrapers-pitt#10]
## Spider Name: 
`alle_airport_authority`

## Website: 
http://www.flypittsburgh.com/about-us/leadership

**Comment by JoelAnderton** [comment]
I'll take this one.

**Comment by biniona** [comment]
I will take this one.

**Comment by biniona** [comment]
Done

**Comment by ben-nathanson** [comment]
Closed by #69
