### ISSUE TITLE
Spider: Housing Opportunity Fund Advisory Board Pittsburgh

### ISSUE THREAD

**Issue by pjsier** [bonfirefan/city-scrapers-pitt#11]
## Spider Name: 
`pitt_housing_opp`

## Website: 
https://www.ura.org/events/housing-opportunity-fund-advisory-board-meeting

**Comment by ben-nathanson** [comment]
I'm working on this. If nothing happens by the end of March, feel free to take a shot at it. 

Thinking about two possible approaches:

Using this [page](www.ura.org/events/housing-opportunity-fund-advisory-board-meeting) is straightforward but only gives us one event - the next meeting. 

On the other hand, I was lucky to discover a [json file](ura.org/events.json) listing all the events. This can be used to return all the events. But I would need to crack some technical challenges. Unfortunately, the json file omits a venue/address for each event. To get those details as well, we would need to pull them from another html or json document. We can query each specific meeting by appending a date at the end such as: https://www.ura.org/events/housing-opportunity-fund-advisory-board-meeting?day=10-3-2019

Opinions/advice appreciated!

**Comment by ben-nathanson** [comment]
Working on this! Feel free to take a shot at it if I haven't submitted a pull request by the end of March.

**Comment by ben-nathanson** [comment]
The spider for this issue is complete - [see the pull request here.](https://github.com/bonfirefan/city-scrapers-pitt/pull/40)

**Comment by ben-nathanson** [comment]
Closed by #40
