### ISSUE TITLE
 Spider: Allegheny Regional Asset District

### ISSUE THREAD

**Issue by pjsier** [bonfirefan/city-scrapers-pitt#13]
## Spider Name: 
`alle_asset_district`

## Website: 
https://radworkshere.org/pages/whats-happening?cal=board-meetings

**Comment by richiebful** [comment]
I'll do this one!

**Comment by bonfirefan** [comment]
@richiebful are you still working on this?

**Comment by richiebful** [comment]
Yeah, I'll try to wrap this one up over the weekend

**Comment by ben-nathanson** [comment]
Closed by #51
