### ISSUE TITLE
Spider: Allegheny County Housing Authority

### ISSUE THREAD

**Issue by pjsier** [bonfirefan/city-scrapers-pitt#17]
## Spider Name: 
`alle_housing`

## Website: 
http://www.achsng.com/

**Comment by cityscrapers-brian** [comment]
Hm... looking at that page at the moment, I don't see any events there.

**Comment by thatKennedy** [comment]
I'm going to try to take this on

**Comment by thatKennedy** [comment]
confirming Brian's observation. doesn't look they have events posted

**Comment by ben-nathanson** [comment]
There are no future meetings posted to the ACHA website so I'm going to close this. 

The ACHA does post meeting notices to the New Pittsburgh Courier. 
[Example](https://newpittsburghcourier.com/2019/01/02/public-notices-1-2-19/) 
[Another Example](https://newpittsburghcourier.com/2019/04/24/public-notices-4-24-19/)

However, these aren't written consistently enough to parse automatically with our current tools.
