### ISSUE TITLE
Spider: Allegheny County Authority for Improvements in Municipalities

### ISSUE THREAD

**Issue by pjsier** [bonfirefan/city-scrapers-pitt#19]
## Spider Name: 
`alle_improvements`

## Website: 
https://www.county.allegheny.pa.us/economic-development/authorities/meetings-reports/aim/meetings.aspx

**Comment by aeternitatis** [comment]
I'll try this one.

**Comment by bonfirefan** [comment]
Hey @eneilly , are you still working on this?

**Comment by synapticarbors** [comment]
As this one seems abandoned, I'll claim it.

**Comment by ben-nathanson** [comment]
Fulfilled by this [PR](https://github.com/bonfirefan/city-scrapers-pitt/pull/57)
