### ISSUE TITLE
Spider: PA Department of Community & Economic Development

### ISSUE THREAD

**Issue by pjsier** [bonfirefan/city-scrapers-pitt#23]
## Spider Name: 
`pa_development`

## Website: 
https://dced.pa.gov/events/

**Comment by ben-nathanson** [comment]
I will work on this spider. If I haven't updated this thread by March 31st, feel free to take a shot at it.

**Comment by ben-nathanson** [comment]
**Work-in-progress/example of what one event looks like :** 

2019-03-11 23:12:38 [scrapy.core.scraper] DEBUG: Scraped from <200 https://dced.pa.gov/wp-json/tribe/events/v1/events>
{'all_day': False,
 'classification': 'todo',
 'description': '',
 'end': datetime.datetime(2019, 10, 2, 16, 15),
 'id': 'pa_development/201910021415/x/pida_board_meeting',
 'links': [{'href': '', 'title': ''}],
 'location': {'address': '400 North Street, Harrisburg, PA, 17120',
              'name': 'KBMC &#8211; Desert Room, Plaza Level, Keystone '
                      'Building'},
 'source': 'https://dced.pa.gov/wp-json/tribe/events/v1/events',
 'start': datetime.datetime(2019, 10, 2, 14, 15),
 'status': 'tentative',
 'time_notes': 'none',
 'title': 'PIDA Board Meeting'}

**Comment by ben-nathanson** [comment]
Fulfilled by [this pull request](https://github.com/bonfirefan/city-scrapers-pitt/pull/38)
