### ISSUE TITLE
Spider: PA Liquor Control Board

### ISSUE THREAD

**Issue by pjsier** [bonfirefan/city-scrapers-pitt#24]
## Spider Name: 
`pa_liquorboard`

## Website: 
https://www.lcb.pa.gov/About-Us/Board/Pages/Public-Meetings.aspx

**Comment by lyons7** [comment]
I'd like to do this one!

**Comment by ben-nathanson** [comment]
Fulfilled by [this pull request](https://github.com/bonfirefan/city-scrapers-pitt/pull/41)
