### ISSUE TITLE
Spider: PA Public Utility Commission

### ISSUE THREAD

**Issue by bonfirefan** [bonfirefan/city-scrapers-pitt#25]
## Spider Name: 
pa_utility

## Website: 
http://www.puc.state.pa.us/about_puc/public_meeting_calendar.aspx

## Scraping Notes:
Jquery calendar

**Comment by skyejinx** [comment]
i'll work on this one

**Comment by bonfirefan** [comment]
@skyejinx Just checking in, are you still working on this?

**Comment by categulario** [comment]
Because I took it this past friday :paintbrush:

**Comment by bonfirefan** [comment]
Ok, thanks @categulario. Make sure to update from upstream, we made some changes!

**Comment by richiebful** [comment]
I'm stealing

**Comment by categulario** [comment]
Feel free to do it. There's some code in my branch that might be useful. It
was almost ready I think

**Comment by ben-nathanson** [comment]
Duplicate of #78
