### ISSUE TITLE
Twisted Error

### ISSUE THREAD

**Issue by nathanderon** [bonfirefan/city-scrapers-pitt#29]
Trying to open up Scrapy shell and I run into this error.

File "c:\users\deron\.virtualenvs\city-scrapers-pitt-gerzyw5n\lib\site-packages\scrapy\_monkeypatches.py", line 20, in <module>
    import twisted.persisted.styles  # NOQA
ModuleNotFoundError: No module named 'twisted'

When trying to install twisted using pipenv install twisted also led to the following:

Installing twisted…
Adding twisted to Pipfile's [packages]…
Installation Succeeded
Pipfile.lock (ab942f) out of date, updating to (fe2388)…
Locking [dev-packages] dependencies…
Success!
Locking [packages] dependencies…
Locking Failed!
...
ERROR: ERROR: Could not find a version that matches wheels

Trying to install wheels gives a similar error.

**Comment by bonfirefan** [comment]
Please refer to #36
