### ISSUE TITLE
Spider: Pittsburgh Mayor's Office of Community Affairs

### ISSUE THREAD

**Issue by bonfirefan** [bonfirefan/city-scrapers-pitt#30]
## Website: 
https://nextdoor.com/profile/2376387/
Example: https://nextdoor.com/news_feed/?post=93922079

## Scraping Notes:
This one will be very tricky, as it requires authenticating with Nextdoor first. Once authenticated, their events load in json form.

**Comment by skyejinx** [comment]
i'll take it!

**Comment by mishugana** [comment]
I've looked somewhat into this and can half-authenticate. 
Would be happy to share what I've learned but would also appreciate help.

**Comment by mishugana** [comment]
I'll take this

**Comment by mishugana** [comment]
I've successfully authenticated, i'll be able to get a list of self-described meetings (contains meeting in title) and their dates, based on the wording of Today, Tonight, or Tomorrow (in combination with the post date) and their descriptions on the nextdoor post. That seems to cover the bulk of the relevant posts being posted.

**Comment by MisterZW** [comment]
@danwarren  and I pulled the old version from @mishugana to try to get it running. It seems like the XPATH to pull out the "csrfmiddlewaretoken" no longer functions correctly (returns None). It is unclear from inspecting NextDoor's login page where such a token would be, and there are no indications that NextDoor has an API or is planning to make one, either.

Anyone looking to work on this would need to find a way to fix the authentication here.

**Comment by mishugana** [comment]
i can take a look at around 5am EST.

**Comment by mishugana** [comment]
actually, can you check to see that the login and password are correct? but
also, there may be a general setting regarding cookies (that normally does
not need to be changed for security), that i should have noted in either
comments or github that may need to be enabled or disabled to have that
work correctly.

**Comment by mishugana** [comment]
btw this is mostly fixed if anyone wants to try it

**Comment by ben-nathanson** [comment]
Closed by #43
