### ISSUE TITLE
Spider: Pittsburgh Public Schools

### ISSUE THREAD

**Issue by jweir136** [bonfirefan/city-scrapers-pitt#33]
## Spider Name: 
0033-spider-pittsburgh_public_schools
## Website: 
https://www.pghschools.org/calendar#calendar1/20190223/month

## Scraping Notes:
Calendar.

**Comment by mishugana** [comment]
Could i work on this?

**Comment by jweir136** [comment]
Sure. Go ahead!  Are you going to use splash since it is JS rendered?

**Comment by mishugana** [comment]
Already mostly written! No need for splash, its actually API driven

**Comment by danwarren** [comment]
@mishugana are you still working on this? I'm happy to jump in and debug.

**Comment by mishugana** [comment]
thanks for the offer,
give me a few more days but if i still dont get around to it by the end of the week then sure!

**Comment by henryCraig** [comment]
Anyone still working on this issue?

**Comment by ben-nathanson** [comment]
Resolved by #42
