### ISSUE TITLE
Spider: City of Pittsburgh Planning Commission

### ISSUE THREAD

**Issue by pjsier** [bonfirefan/city-scrapers-pitt#4]
## Spider Name: 
`pitt_city_planning`

## Website: 
http://pittsburghpa.gov/dcp/notices

## Scraping Notes:
This is a plain text with event names as ‘p tags’ and details as ‘ul’ //an unordered list

According to the [Pittsburgh Planning Commission](http://apps.pittsburghpa.gov/dcp/Planning_Commission.pdf), meetings are every other Tuesday around 1pm, downtown on the 1st floor of the Civic Building at 200 Ross Street. 

Notices of hearing appear to be posted at http://pittsburghpa.gov/dcp/notices

> City   Planning   Commission   meetings   are   held   every   
> other Tuesday beginning in the early afternoon. They are 
> located downtown on the 1st floor of the Civic Building at 
> 200 Ross Street.   
> Planning  Commission  agendas,  applicant  presentations,  
> and minutes are posted online at pittsburghpa.gov/dcp/  
> From  the  City  Planning  home  page,  click  on  “Planning  
> Commission”  on  the  right  hand  menu.  To  receive  the  
> agenda   by   email,   please   contact   Dolores   Hanna   at         
> dolores.hanna@pittsburghpa.gov or 412-255-2473.
> Briefing
> At  approximately    1  PM,  the  Commission  hears  project  
> briefings off of the official record.  The public is welcome to 
> observe, but no public comments are taken.  The briefing 
> portion of the meeting provides an initial presentation to 
> the Commission, then projects return in two weeks on the 
> Hearing and Action agenda.  
> Hearing and Action
> Hearing   and   Action   begins   no   earlier   than   2   PM.      
> Applicants   make   a   presentation   again,   including   any   
> revisions   or   additional   information   requested   by   the   
> Commission  during  briefing.    Public  comment  is  then  
> accepted—limited  to  3  minutes  per  person,  per  project.    
> The  Commission  usually  votes  on  projects  the  same  day  
> they are presented for Hearing and Action.

**Comment by skyejinx** [comment]
im working on it!

**Comment by jtotoole** [comment]
i'll take!

**Comment by jtotoole** [comment]
looks like someone else already took this according to the spreadsheet

**Comment by bonfirefan** [comment]
Hey @jtotoole, yes @dkori and @nathanderon are working on this

**Comment by ben-nathanson** [comment]
Closed by #54
