### ISSUE TITLE
Add new Meeting Statuses to documentation and project

### ISSUE THREAD

**Issue by bonfirefan** [bonfirefan/city-scrapers-pitt#49]
In order to better track meetings, we will add RESCHEDULED and UPDATED as meeting statuses. Comes up in Issue #16 and in the general last-minute rescheduling of meetings.

**RESCHEDULED** means the meeting was moved to a new date
**UPDATED** is the new meeting time of a meeting.

Statuses are now:
- CANCELLED
- TENTATIVE
- CONFIRMED
- PASSED
- **RESCHEDULED**
- **UPDATED**

We'll need to add Pittsburgh-specific documentation reflecting this.

**Comment by ben-nathanson** [comment]
We don't have Pittsburgh-specific docs yet, right? I could start it out in markdown and if we decide to do a website later we can port the contents over to HTML.

**Comment by bonfirefan** [comment]
I think this is a good idea, especially for onboarding

**Comment by bonfirefan** [comment]
The markdown docs already exist in the project!

**Comment by ben-nathanson** [comment]
Closed by PR #84
