### ISSUE TITLE
Spider: Urban Redevelopment Authority of Pittsburgh

### ISSUE THREAD

**Issue by pjsier** [bonfirefan/city-scrapers-pitt#5]
## Spider Name: 
`pitt_urbandev`

## Website: 
 Meetings of the URA Board of Directors are held on the second Thursday of each month at 2 p.m. in the Wherrett Room on the 13th floor at 200 Ross Street, Pittsburgh, PA 15219. https://www.ura.org/pages/board-meeting-notices-agendas-and-minutes

**Comment by skyejinx** [comment]
i'm working on it!

**Comment by skyejinx** [comment]
i'm working on it

**Comment by bonfirefan** [comment]
@skyejinx you still working on this?

**Comment by skyejinx** [comment]
yep yep

**Comment by bonfirefan** [comment]
Awesome, thanks @skyejinx. It does look another one of the issues you claimed was reclaimed by someone else, but this is still all yours!

**Comment by ben-nathanson** [comment]
I'm working on this. Should be wrapped up by the end of February.

**Comment by ben-nathanson** [comment]
Closed by #86
