### ISSUE TITLE
pipenv install errors

### ISSUE THREAD

**Issue by jeslevine** [bonfirefan/city-scrapers-pitt#50]
$ pipenv install
Installing dependencies from Pipfile.lock (32f095)▒
An error occurred while installing scrapy==1.6.0 --hash=sha256:4ec03552c9aed1e82a376488150e904e0213bdee3ca140225105e9b03d0de204 --hash=sha256:558dfd10ac53cb324ecd7eefd3eac412161c7507c082b01b0bcd2c6e2e9f0766! Will try again.
An error occurred while installing scrapy-sentry==0.9.0 --hash=sha256:4c78e0fb5a5940639f11ae2a1fb28d4ea1a41180d88289efc6d8e39e1e14227f! Will try again.

An error occurred while installing twisted==19.2.0 --hash=sha256:1708e1928ae84ec9d3ebab0d427e20e1e38ff721b15bbced476d047d4a43abbe --hash=sha256:3716eca1c80ef88729a85e9a70f09acce8df2adf7c58590d54c94f383945bc47! Will try again.
Installing initially failed dependencies▒

**Comment by bonfirefan** [comment]
Refer to #36
