### ISSUE TITLE
Add to documentation for commit instructions: YAPF

### ISSUE THREAD

**Issue by wsnavely** [bonfirefan/city-scrapers-pitt#73]
Currently we hit YAPF issues in travis occasionally. We might want to add some documentation to help developers run YAPF before they check in, and fix any formatting problems.

To show YAPF discrepancies we can run:
`yapf --diff -r .`

After doing this, developers can either apply the changes manually, or automatically apply them with:
`yapf -r -i .`

**Comment by wsnavely** [comment]
Sorry, I'm not sure how to remove the "New Spider" label. This isn't a new spider.

**Comment by ben-nathanson** [comment]
I will add this to the new documentation

**Comment by ben-nathanson** [comment]
This is resolved in #84. See the file `04-development.md`.
