### ISSUE TITLE
Master Documentation Issues

### ISSUE THREAD

**Issue by maxachis** [bonfirefan/city-scrapers-pitt#83]
- [Twisted Error using 'pipenv install twisted #36](url="https://github.com/bonfirefan/city-scrapers-pitt/issues/36")
- [Updates from "upstream" not integrating in local environment - Solved #68](url="https://github.com/bonfirefan/city-scrapers-pitt/issues/68")
- [SSL: CERTIFICATE_VERIFY_FAILED error #64](url="https://github.com/bonfirefan/city-scrapers-pitt/issues/64")
- [city-scrapers-core module not found #60](url="https://github.com/bonfirefan/city-scrapers-pitt/issues/60")

**Comment by thatKennedy** [comment]
- \r when running scrapy [#85 ](url)

**Comment by ben-nathanson** [comment]
Resolved by #84
