### ISSUE TITLE
Spider: Pittsburgh Department of Mobility and Infrastructure

### ISSUE THREAD

**Issue by pjsier** [bonfirefan/city-scrapers-pitt#9]
## Spider Name: 
`pitt_mobility`

## Website: 
http://pittsburghpa.gov/domi/index.html

**Comment by cityscrapers-brian** [comment]
Lemme see what I can do here...

**Comment by cityscrapers-brian** [comment]
Huh... appears to be no events on that page at the moment.

**Comment by ben-nathanson** [comment]
This department does not appear to have consistent meetings so I am going to close this issue.
